title: "Trial and Errir"
author: "Siddhi Lad"
description: "A personal blog where I document my projects."
url: "https://png270.github.io"  # base URL
baseurl: ""                      # must be empty for user pages

github_username: png270

header_pages:
  - index.md
  - about.md   # uncomment if you want About back

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
