title: "Breachy270"
author: "Siddhi Lad"
description: "A personal blog where I document my projects."
url: "https://png270.github.io"  # base URL
baseurl: ""                      # must be empty for user pages

github_username: png270

header_pages:
  - index.md
  - about.md

style: dark # dark (default), light or hacker
listen_for_clients_preferred_style: true # false (default) or true

footer: 'Contact <a href="https://www.linkedin.com/in/siddhi-lad/">LinkedIn</a> - <a href="https://github.com/png270">GitHub</a>'

google_analytics: UA-NNNNNNNN-N
disable_google_fonts: true


# Build settings
remote_theme: b2a3e8/jekyll-theme-console@76983908faa6f06ffd87b70165f2632790d36687
plugins:
  - jekyll-feed
  - jekyll-remote-theme
