title: "Trial and Errir"
author: "Siddhi Lad"
description: "A personal blog where I document my projects."
url: "https://png270.github.io"  # base URL
baseurl: ""                      # must be empty for user pages

github_username: png270

header_pages:
  - index.md
  - about.md

style: dark # dark (default), light or hacker
listen_for_clients_preferred_style: true # false (default) or true

footer: 'follow us on <a href="https://twitter.com/xxx">twitter</a>'

google_analytics: UA-NNNNNNNN-N
disable_google_fonts: false


# Build settings
remote_theme: b2a3e8/jekyll-theme-console
plugins:
  - jekyll-feed
  - jekyll-remote-theme
